page_analyzer/__init__.py
from page_analyzer.app import create_app

__all__ = ['create_app']

page_analyzer/app.py
from time import strftime
from flask import Flask, render_template


def create_app():

    app = Flask(__name__)
    app.config.from_pyfile('config.py')

    @app.template_filter()
    def format_datetime(value):
        return strftime('%Y-%m-%d %H:%M:%S', value.timetuple())

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('errors/404.html'), 404

    from page_analyzer import views
    app.register_blueprint(views.bp)
    return app

page_analyzer/views.py
from flask import Blueprint
from bs4 import BeautifulSoup
from flask import abort, flash, render_template
from flask import request, redirect, url_for
from itertools import zip_longest
import requests
from urllib.parse import urlparse
from sqlalchemy import desc
from page_analyzer.db import get_db, get_table


bp = Blueprint('urls', __name__)


def validate_url(url):
    if not url:
        return False
    if len(url) > 255:
        return False
    o = urlparse(url)
    if not (o.netloc and o.scheme):
        return False
    return True


def normalize(url):
    o = urlparse(url)
    return f'{o.scheme}://{o.netloc}'


def parse_page(page):
    soup = BeautifulSoup(page, 'html.parser')
    title = soup.find('title').text
    h1 = soup.find('h1').text
    description = soup.find('meta', attrs={'name': 'description'})
    if description:
        description = description['content']
    return {
        'title': title,
        'h1': h1,
        'description': description,
    }


@bp.route('/', methods=['GET', 'POST'])
def index():
    engine = get_db()
    urls_table = get_table('urls')
    if request.method == 'POST':
        url = request.form['url']

        if not validate_url(url):
            flash('Некорректный URL', 'danger')
            return redirect(url_for('urls.index'))

        normalized_url = normalize(url)
        with engine.begin() as connection:
            existed_url = connection.execute(
                urls_table.select().
                where(urls_table.c.name == normalized_url)).first()
            if existed_url:
                url_id = existed_url.id
                flash('Страница уже существует', 'info')

            else:
                new_url = connection.execute(
                    urls_table.insert().values(
                        name=normalized_url,))
                print('Value inserted!')

                url_id = new_url.inserted_primary_key[0]
            return redirect(url_for('urls.get_url', id=url_id))

    return render_template('index.html')


@bp.route('/urls')
def urls():
    engine = get_db()
    urls_table = get_table('urls')
    urls_checks = get_table('urls_checks')
    with engine.begin() as conn:
        url_list = conn.execute(urls_table.select().order_by('id')).fetchall()
        print('URL_LIST ====> ', url_list)
        checks = conn.execute(
            urls_checks.select().
            distinct('url_id').
            order_by('url_id').
            order_by(desc('created_at'))
        ).fetchmany()
        print('CHECKS ====> ', checks)

    return render_template(
        'urls/index.html',
        urls=zip_longest(url_list, checks),
    )


@bp.route('/urls/<int:id>')
def get_url(id):
    engine = get_db()
    urls_table = get_table('urls')
    urls_checks = get_table('urls_checks')
    with engine.begin() as connection:
        url = connection.execute(
            urls_table.select().
            where(urls_table.c.id == id)).first()
        print('URL ==== ', url)
        if url is None:
            abort(404)
        checks = connection.execute(
            urls_checks.select().where(urls_checks.c.url_id == id)
        )
        checks = sorted(checks, key=lambda x: x.created_at, reverse=True)

    return render_template('urls/url.html', url=url, checks=checks)


@bp.route('/urls/<int:id>/checks', methods=['POST'])
def url_checks(id):
    engine = get_db()
    urls_table = get_table('urls')
    urls_checks = get_table('urls_checks')
    with engine.begin() as connection:
        url = connection.execute(
            urls_table.select().
            where(urls_table.c.id == id)).first()
        try:
            response = requests.get(url.name)
        except requests.ConnectionError:
            flash('Не удалось получить данные', 'danger')
            return redirect(url_for('urls.get_url', id=id))

        page = response.text
        parsed_page = parse_page(page)
        connection.execute(
            urls_checks.insert().values(
                url_id=id,
                status_code=response.status_code,
                h1=parsed_page['h1'],
                title=parsed_page['title'],
                description=parsed_page['description'],
            )
        )
        flash('Страница успешно проверена', 'info')

        return redirect(url_for('urls.get_url', id=id))

page_analyzer/templates/index.html
{% extends 'layout.html' %}

{% block content %}
<main class="flex-grow-1">
<div class="container-lg mt-3">
    <div class="row">
        <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
        <h1 class="display-3">Анализатор страниц</h1>
        <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
        <form method="post" class="d-flex justify-content-center">
            <input type="text" name="url" placeholder="https://www.example.com" value="{{ request.form['url'] }}" class="form-control form-control-lg"></input>
            <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
        </form>
        </div>
    </div>
</div>
</main>
{% endblock %}

page_analyzer/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>Анализатор страниц</title>
</head>
<body class="min-vh-100 d-flex flex-column">
<header class="flex-shrink-0">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
      <a class="navbar-brand" href="{{ url_for('urls.index') }}">Анализатор страниц</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <li class="nav-item">
                  <a class="nav-link " href="{{ url_for('urls.urls') }}">Сайты</a>
              </li>
          </ul>
      </div>
  </nav>
</header>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
      {% endfor %}
    {% endif %}
    {% endwith %}

    {% block content %}
    {% endblock %}
</body>
<footer class="border-top py-3 mt-5 flex-shrink-0">
    <div class="container-lg">
        <div class="text-center">
            <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
        </div>
    </div>
</footer>
</html>

page_analyzer/templates/urls/checks.html
{% extends url.html %}

{% block checks %}
{% for check in checks %}
    <tr>
    <td>{{ check.id }}</td>
    <td>Код ответа</td>
    <td>h1</td>
    <td>title</td>
    <td>description</td>
    <td>{{ check.created_at|format_datetime }}</td>
    </tr>
{% endfor %}
{% endblock %}

page_analyzer/templates/urls/index.html
{% extends 'layout.html' %}

{% block content %}
<main class="flex-grow-1">
    <div class="container-lg">
<h1 class="mt-5 mb-3">Сайты</h1>
    <div class="table-responsive">
    <table class="table table-bordered table-hover text-nowrap">
        <tr>
        <th>ID</th>
        <th>Имя</th>
        <th>Последняя проверка</th>
        <th>Код ответа</th>
        </tr>
        {% for url, check in urls %}
        <tr>
        <td>{{ url.id }}</td>
        <td><a href="{{ url_for("urls.get_url", id=url.id) }}">{{ url.name }}</a></td>
        {% if check %}
        <td>{{ check.status_code }}</td>
        <td>{{ check.created_at|format_datetime }}</td>
        {% else %}
        <td></td>
        <td></td>
        {% endif %}
        </tr>
        {% endfor %}
    </table>
    </div>
    </div>
</main>
{% endblock %}

page_analyzer/templates/urls/url.html
{% extends 'layout.html' %}

{% block content %}
<main class="flex-grow-1">
    <div class="container-lg">
    <h1 class="mt-5 mb-3">Сайт: {{ url.name }}</h1>
        <div class="table-responsive">
        <table class="table table-bordered table-hover text-nowrap">
            <tr><td>ID</td><td>{{ url.id }}</td></tr>
            <tr><td>Имя</td><td>{{ url.name }}</td></tr>
            <tr><td>Дата создания</td><td>{{ url.created_at|format_datetime }}</td></tr>
        </table>
        </div>

    <h2 class="mt-5 mb-3">Проверки</h2>
    <form method="post" action="{{ url_for('urls.url_checks', id=url.id) }}">
    <input type="submit" class="btn btn-primary" value="Запустить проверку">
    </form>

    <table class="table table-bordered table-hover text-nowrap">
    <tr>
        <th>ID</th>
        <th>Код ответа</th>
        <th>h1</th>
        <th>title</th>
        <th>description</th>
        <th>Дата создания</th>
    </tr>
    {% for check in checks %}
    <tr>
        <td>{{ check.id }}</td>
        <td>{{ check.status_code }}</td>
        <td>{{ check.h1 }}</td>
        <td>{{ check.title }}</td>
        <td>{{ check.description }}</td>
        <td>{{ check.created_at|format_datetime }}</td>
    </tr>
    {% endfor %}
    </table>
    </div>
</main>
{% endblock %}